### ISSUE TITLE
Two missing files and an a build error

### ISSUE THREAD

**Issue by lockbox23** [tromgy/service-base#1]
First and foremost, thank you for posting this repository! Awesome!

I'm going through the sample-service and it appears there are two files missing - resource.h and resource1.h. Am I supposed to create these myself?

The error I'm getting is in sample-service.cpp, indentifier "Appendix" is undefined.

`
else if (_wcsicmp((Appendix E) (Appendix E) (Appendix E), argv[1]) == 0) 
`

I'm using Visual Studio 2019,

**Comment by tromgy** [comment]
Those missing files (**resource.h** and **resource1.h**) must have been some dead artifacts from the original MS project. They are not there, and are not used anywhere. I have now removed the references from the project, and you can refetch  to get these changes.

Regarding your build error, I don't know how you ended up with this. This is definitely _not_  the code that is in the git repository. It looks like you had some errant search/replace taking place?

Just to make sure, I pulled the code into a system with Visual Studio 2019 installed, and built both solutions in all 4 platform/build configurations.

**Comment by lockbox23** [comment]
All good now. Thank you.
