### ISSUE TITLE
error using "-start-type"

### ISSUE THREAD

**Issue by rombust** [tromgy/service-base#4]
In "sample-service.cpp",
                               PCWSTR wsStartType = argv[++i];
                                if (regex_match(wsStartType, wregex(L"[2-4]")))
                                {
  ---->                              dwSvcStartType = _wtol(argv[++i]);
I believe should say:
   ---->                              dwSvcStartType = _wtol(wsStartType]);

This fixes a crash when using "install -start-type" using the command line

**Comment by tromgy** [comment]
Good catch! Thanks for reporting. Should be fixed now.
