### ISSUE TITLE
help

### ISSUE THREAD

**Issue by gabriel-maxx** [tromgy/service-base#5]
I'm using the service and it's working perfectly, but I wanted to set a time for the service to stop, for example: when the service starts I want it to stop automatically after 1 minute...
how you do it? what do I have to edit in the project?

**Comment by tromgy** [comment]
You can simply start another thread that will wait for the desired interval and then call the `Stop` method on the service class.

Here's an example:

in **SampleService.h** add a static method to the `CSampleService` class:

```
static DWORD __stdcall  ServiceTerminator(void* self);
```

and implement it in **SampleService.cpp** as follows:

```
DWORD __stdcall CSampleService::ServiceTerminator(void* self)
{
   CSampleService* pService = (CSampleService*)self;

   Sleep(60000);
   pService->Stop();

   return 0;
}
```

Then create the thread that will run this method right after you create the thread to run the service:

```
      // Add the main service function for execution in a worker thread.
      if (!CreateThread(NULL, 0, ServiceRunner, this, 0, NULL))
      {
         WriteLogEntry(L"Sample Service couldn't create worker thread.", EVENTLOG_ERROR_TYPE, MSG_STARTUP, CATEGORY_SERVICE);
      }

      // Create the terminator thread
      if (!CreateThread(NULL, 0, ServiceTerminator, this, 0, NULL))
      {
         WriteLogEntry(L"Sample Service couldn't create terminator thread.", EVENTLOG_ERROR_TYPE, MSG_STARTUP, CATEGORY_SERVICE);
      }
```

**Comment by gabriel-maxx** [comment]
@tromgy  thank you very much, i did what you said and it worked. but i have one last question:
how do i use svchost.exe to host the service instead of creating a new normal process? what do i have to edit in the code?

**Comment by tromgy** [comment]
The short answer is that you build your service as a DLL and then register it with svchost. The long answer can be found here: https://www.geoffchappell.com/studies/windows/win32/services/svchost/index.htm

**Comment by gabriel-maxx** [comment]
> The short answer is that you build your service as a DLL and then register it with svchost. The long answer can be found here: https://www.geoffchappell.com/studies/windows/win32/services/svchost/index.htm

could you explain briefly using your project please? for example: I compiled it with visual studio 2019 in "dll" format and now I have sample-service.dll, what do I do now?

before, it compiled in "exe" format and used the command "sample-service install -start-type 2 -account LocalSystem Account"
sc start sample-service

**Comment by tromgy** [comment]
It involves more than just compiling as a DLL, you need to export the `ServiceMain` main function, and set some registry keys so that **svchost** can find your service DLL. The article I've mentioned has more details. I don't have any first-hand experience with DLL services, but you can use the [stackoverflow site](https://stackoverflow.com) if you need more help.
