### ISSUE TITLE
The sample-service does not compile

### ISSUE THREAD

**Issue by Ghost53574** [tromgy/service-base#7]
To reproduce open a developers console for VS2022:
1. git clone https://github.com/tromgy/service-base
2. cd .\service-base\sample-service\
3. devenv .\sample-service.sln
4. Click Build

Result: 
LNK1104	cannot open file 'service-base.lib'

Expected Result:
A debug build of sample-service.exe as shown in your Readme.md

-
What I've tried to fix this issue?

I've tried creating my own static library and organizing the code as such with extern's, but the ultimate result is that I can't seem to export any of the functions correctly. So I decided to post an issue here since from my understanding that the sample-service should work right out of the box.

Thank you

**Comment by tromgy** [comment]
You could just build the **service-base** solution first. But I see your point, it makes sense to make the **sample-service** project depend on **service-base**. Then it would build it as a dependency.

**Comment by Ghost53574** [comment]
Oh, wow, I was confused with the structure of the project. Thank you so much!
